// Generated by CoffeeScript 1.5.0
(function() {

  Handlebars.registerHelper('cache', function(url) {
    var hash, _ref;
    hash = typeof __meteor_runtime_config__ !== "undefined" && __meteor_runtime_config__ !== null ? (_ref = __meteor_runtime_config__.staticURLHashes) != null ? _ref[url] : void 0 : void 0;
    if (hash) {
      return '/cache' + url + '?' + hash;
    } else {
      throw new Error('in "cache" template helper, url is not a known static resource: ' + url);
    }
  });

}).call(this);
